AllCops:
  Excludes:
    - db/**/*
    - config/**/*
    - script/**
    - spec/**/*
    - lib/**/*
    - bin/*
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 125
Style/FrozenStringLiteralComment:
  Enabled: false