defaults: &defaults
    god:
      - all
    admin:
      api/v1/shops:
        - all
      api/v1/products:
        - all
      api/v1/orders:
        - all
      api/v1/customers:
        - all
    seller:
      api/v1/shops:
        - show
      api/v1/products:
        - all
      api/v1/customers:
        - all
      api/v1/orders:
        - all

test:
    <<: *defaults
development:
    <<: *defaults
staging:
    <<: *defaults
production:
    <<: *defaults
