defaults: &defaults
    god:
      - all
    admin:
      api/v1/shops:
        - all
      api/v1/products:
        - all
    seller:
      api/v1/shops:
        - show # ???!!! shop < = > user ids
      api/v1/products:
        - all # ???!!! shop < = > user ids

test:
    <<: *defaults
development:
    <<: *defaults
staging:
    <<: *defaults
production:
    <<: *defaults
